Authorization.go file is disabled
octoposprime/op-be-gw pull request #78
Opened 2024-05-19 15:28 UTC by Smnrgcl

Close #66

2024-05-20 06:38 UTC, Feyzanrs approved these changes

2024-05-20 06:43 UTC, Feyzanrs requested changes
Please revert the changes in the internal/application/service/authorization.go file as the modifications were only required in the pkg/infrastructure/adapter/service/authorization.go file.

2024-05-20 15:21 UTC, Feyzanrs approved these changes

2024-05-21 12:19 UTC, Sddilora approved these changes
👍🏻

2024-05-21 12:19 UTC, merged