Update error.go
octoposprime/op-be-gw pull request #82
Opened 2024-05-21 13:25 UTC by mervegonc

implement ErrorDlrNotFound

2024-05-21 14:14 UTC, husamettinarabaci requested changes

2024-05-21 14:14 UTC, husamettinarabaci commented on internal/domain/model/object/error.go
> +	return []error{
You have to add all error in the 
var ERRORS []error
and return that.

2024-05-21 14:44 UTC, Sddilora requested changes
You will also add ErrorDlrNotFound to 
```go
var ERRORS []error = []error{
	ErrorNone,
	ErrorUserNotFound,
}
```
 here

2024-05-22 07:02 UTC, husamettinarabaci commented
> You will also add ErrorDlrNotFound to 
> 
> ```go
> 
> var ERRORS []error = []error{
> 
> 	ErrorNone,
> 
> 	ErrorUserNotFound,
> 
> }
> 
> ```
> 
>  here

> And you have to returnt ERRORS

2024-05-22 14:48 UTC, Sddilora requested changes

2024-05-22 14:48 UTC, Sddilora commented on internal/domain/model/object/error.go
> +	}
You need to return ERRORS :)

2024-06-01 06:12 UTC, closed without merging