Fix/mrv/51/dlr add err
octoposprime/op-be-gw pull request #86
Opened 2024-05-23 14:27 UTC by mervegonc

Closes #51 add dlr error

2024-05-23 17:58 UTC, Sddilora requested changes
"But the return value is correct this time." 👍🏻

2024-05-23 17:58 UTC, Sddilora commented on internal/domain/model/object/error.go
> +	ErrDlr  string = "dlr",
"Comma unexpected." :') 
https://github.com/octoposprime/op-be-user/blob/be5ffaaaef4aac058f16bef029f055c64fcb12b5/internal/domain/model/object/error.go#L36-L47

2024-05-23 18:01 UTC, Sddilora commented
D'accord
S'il vous plaît
Corrigez
Le
Titre
De
La
Demande de tirage (pull request)

2024-05-25 14:57 UTC, mervegonc commented on internal/domain/model/object/error.go
> +	ErrDlr  string = "dlr",
finally, thanks to you <3

2024-05-25 15:02 UTC, mervegonc commented on internal/domain/model/object/error.go
> +	ErrDlr  string = "dlr",
i fixed my syntax err, ı guess :|

2024-05-25 15:03 UTC, mervegonc commented
> "But the return value is correct this time." 👍🏻

thanks to you <3

2024-05-25 15:05 UTC, mervegonc commented
> D'accord S'il vous plaît Corrigez Le Titre De La Demande de tirage (pull request)

Do you comment when you are bored,
in french?

2024-05-27 11:03 UTC, Sddilora commented
Our title needs to describe what we have done in this PR. "dlr add err" might refer to any error on DLR, so it could mean several things a month later, leading to potential trouble in managing our previous processes. We need to choose a more descriptive name, such as "Add 'ErrorDlrNotFound' to errors," so that we can understand what we have merged in this PR not only now but also a month or even a year later. Thank you for considering this change.

2024-05-27 11:07 UTC, Sddilora commented
> > D'accord S'il vous plaît Corrigez Le Titre De La Demande de tirage (pull request)
> 
> Do you comment when you are bored, in french?

No, I was not bored. I'm sorry, but I got frustrated because we've discussed this problem many times and we're still encountering it. It seems like we're not giving our tasks the attention they deserve, and it puts a lot of pressure on our leads for small matters.

2024-06-01 06:11 UTC, Sddilora approved these changes

2024-06-01 06:26 UTC, Feyzanrs approved these changes

2024-06-01 06:35 UTC, merged